version: '3.8'

services:
  cms:
    build:
      context: .
      dockerfile: apps/cms/Dockerfile
    container_name: compro-layangdigital-cms
    restart: always
    ports:
      - "1337:1337"
    environment:
      - DATABASE_CLIENT=postgres
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT:-5432}
      - DATABASE_NAME=${DATABASE_NAME:-super_saturn}
      - DATABASE_USERNAME=${DATABASE_USERNAME:-strapi}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD:-strapi}
      - APP_KEYS=${APP_KEYS}
      - API_TOKEN_SALT=${API_TOKEN_SALT}
      - ADMIN_JWT_SECRET=${ADMIN_JWT_SECRET}
      - TRANSFER_TOKEN_SALT=${TRANSFER_TOKEN_SALT}
      - JWT_SECRET=${JWT_SECRET}
      - NODE_ENV=production


  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    container_name: compro-layangdigital-web
    restart: always
    ports:
      - "3000:80"


